### ISSUE TITLE
Should tell the user when there's an error loading a file

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#77]
Currently HypeDyn silently fails when there's an error loading the file (if, for example, there's a problem with the file format). We should let the user know what happened (at least pop up an error dialogue).

**Comment by lexaay** [comment]
Still seems to hang silently when I try to load an invalid file. For example, opening an empty file named Untitled.dyn2 results in the following exception, and doesn't show anything to the user, with HypeDyn unresponsive:

```
2016-03-05 15:40:35.617 [JavaFX Application Thread] INFO  - LoadRequest ("src" -> "UI")
2016-03-05 15:40:35.619 [JavaFX Application Thread] INFO  - LoadResponse ("src" -> "Core")
2016-03-05 15:41:02.664 [JavaFX Application Thread] INFO  - LoadFromFile ("file" -> /Users/alex/Desktop/Untitled.dyn2, "src" -> "UI")
2016-03-05 15:41:02.694 [JavaFX Application Thread] ERROR - 
java.lang.ClassCastException: org.narrativeandplay.hypedyn.serialisation.AstNothing$ cannot be cast to org.narrativeandplay.hypedyn.serialisation.AstMap
	at org.narrativeandplay.hypedyn.events.CoreEventDispatcher$$anonfun$22.apply(CoreEventDispatcher.scala:168) ~[hypedyn-core.jar:na]
	at org.narrativeandplay.hypedyn.events.CoreEventDispatcher$$anonfun$22.apply(CoreEventDispatcher.scala:166) ~[hypedyn-core.jar:na]
	at rx.lang.scala.ImplicitFunctionConversions$$anon$4.call(ImplicitFunctionConversions.scala:73) ~[rxscala_2.11-0.25.1.jar:0.25.1]
	at rx.Observable$27.onNext(Observable.java:8002) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter.java:54) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:223) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:114) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:118) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:65) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.lang.scala.Subject$class.onNext(Subject.scala:36) ~[rxscala_2.11-0.25.1.jar:0.25.1]
	at rx.lang.scala.subjects.SerializedSubject.onNext(SerializedSubject.scala:46) ~[rxscala_2.11-0.25.1.jar:0.25.1]
	at org.narrativeandplay.hypedyn.events.EventBus$.send(EventBus.scala:24) ~[hypedyn-api-0.22.2.jar:na]
	at org.narrativeandplay.hypedyn.events.UiEventDispatcher$.requestLoad(UiEventDispatcher.scala:214) ~[hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$org$narrativeandplay$hypedyn$uicomponents$Menubar$$anon$$handle$body$2$1.apply(Menubar.scala:59) ~[hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$org$narrativeandplay$hypedyn$uicomponents$Menubar$$anon$$handle$body$2$1.apply(Menubar.scala:58) ~[hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.events.UiEventDispatcher$.requestExit(UiEventDispatcher.scala:288) ~[hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3.org$narrativeandplay$hypedyn$uicomponents$Menubar$$anon$$handle$body$2(Menubar.scala:58) ~[hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$2.handle(Menubar.scala:57) ~[hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$2.handle(Menubar.scala:57) ~[hypedyn-ui.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$20(GlobalMenuAdapter.java:153) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.GlobalMenuAdapter$$Lambda$136/918775356.handle(Unknown Source) ~[na:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234) ~[jfxrt.jar:na]
2016-03-05 15:41:35.459 [JavaFX Application Thread] INFO  - LoadRequest ("src" -> "UI")
2016-03-05 15:41:46.535 [JavaFX Application Thread] INFO  - NewStoryRequest ("src" -> "UI")
2016-03-05 15:41:48.707 [JavaFX Application Thread] INFO  - LoadRequest ("src" -> "UI")
2016-03-05 15:41:51.867 [JavaFX Application Thread] INFO  - LoadFromFile ("file" -> /Users/alex/Desktop/Untitled.dyn2, "src" -> "UI")
2016-03-05 15:41:55.338 [JavaFX Application Thread] INFO  - LoadFromFile (
  "file" -> /Users/alex/Desktop/study2/external_numbers-ondemand.dyn2,
  "src" -> "UI")
```

**Comment by lexaay** [comment]
Now it seems to catch the error and show a dialog, but any subsequent attempts to open a file show the file dialog but nothing happens after this - no error, but no file loaded. 

For example, trying to open the file "Untitled.dyn", which is an empty file, shows the error dialog, but trying to open file "LRRH5.dyn2" after this results in nothing - no error, and no loaded file. 

Here's the log:

```
:run
2016-03-07 22:18:57.478 [JavaFX Application Thread] INFO  - UndoStatus ("isAvailable" -> false, "src" -> "Undo")
2016-03-07 22:18:57.514 [JavaFX Application Thread] INFO  - RedoStatus ("isAvailable" -> false, "src" -> "Undo")
2016-03-07 22:19:04.441 [JavaFX Application Thread] INFO  - LoadRequest ("src" -> "UI")
2016-03-07 22:19:04.442 [JavaFX Application Thread] INFO  - LoadResponse ("src" -> "Core")
2016-03-07 22:19:11.269 [JavaFX Application Thread] INFO  - LoadFromFile ("file" -> /Users/alex/Desktop/Untitled.dyn2, "src" -> "UI")
2016-03-07 22:19:11.295 [JavaFX Application Thread] ERROR - File loading error
java.lang.ClassCastException: org.narrativeandplay.hypedyn.serialisation.AstNothing$ cannot be cast to org.narrativeandplay.hypedyn.serialisation.AstMap
	at org.narrativeandplay.hypedyn.events.CoreEventDispatcher$$anonfun$22.apply(CoreEventDispatcher.scala:169) ~[hypedyn-core.jar:na]
	at org.narrativeandplay.hypedyn.events.CoreEventDispatcher$$anonfun$22.apply(CoreEventDispatcher.scala:167) ~[hypedyn-core.jar:na]
	at rx.lang.scala.ImplicitFunctionConversions$$anon$4.call(ImplicitFunctionConversions.scala:73) ~[rxscala_2.11-0.25.1.jar:0.25.1]
	at rx.Observable$28.onNext(Observable.java:8050) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[rxjava-1.0.17.jar:1.0.17]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54) [rxjava-1.0.17.jar:1.0.17]
	at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter.java:54) [rxjava-1.0.17.jar:1.0.17]
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:223) [rxjava-1.0.17.jar:1.0.17]
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:114) [rxjava-1.0.17.jar:1.0.17]
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150) [rxjava-1.0.17.jar:1.0.17]
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:118) [rxjava-1.0.17.jar:1.0.17]
	at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:65) [rxjava-1.0.17.jar:1.0.17]
	at rx.lang.scala.Subject$class.onNext(Subject.scala:36) [rxscala_2.11-0.25.1.jar:0.25.1]
	at rx.lang.scala.subjects.SerializedSubject.onNext(SerializedSubject.scala:46) [rxscala_2.11-0.25.1.jar:0.25.1]
	at org.narrativeandplay.hypedyn.events.EventBus$.send(EventBus.scala:24) [hypedyn-api-0.22.2.jar:na]
	at org.narrativeandplay.hypedyn.events.UiEventDispatcher$.requestLoad(UiEventDispatcher.scala:218) [hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$org$narrativeandplay$hypedyn$uicomponents$Menubar$$anon$$handle$body$2$1.apply(Menubar.scala:59) [hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$org$narrativeandplay$hypedyn$uicomponents$Menubar$$anon$$handle$body$2$1.apply(Menubar.scala:58) [hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.events.UiEventDispatcher$.requestExit(UiEventDispatcher.scala:292) [hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3.org$narrativeandplay$hypedyn$uicomponents$Menubar$$anon$$handle$body$2(Menubar.scala:58) [hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$2.handle(Menubar.scala:57) [hypedyn-ui.jar:na]
	at org.narrativeandplay.hypedyn.uicomponents.Menubar$$anon$3$$anonfun$2.handle(Menubar.scala:57) [hypedyn-ui.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$20(GlobalMenuAdapter.java:153) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.GlobalMenuAdapter$$Lambda$136/1785731093.handle(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234) [jfxrt.jar:na]
2016-03-07 22:19:11.301 [JavaFX Application Thread] INFO  - Error (
  "msg" -> "An error occurred while trying to load the story",
  "throwable" -> java.lang.ClassCastException: org.narrativeandplay.hypedyn.serialisation.AstNothing$ cannot be cast to org.narrativeandplay.hypedyn.serialisation.AstMap,
  "src" -> "Core")
2016-03-07 22:19:37.004 [JavaFX Application Thread] INFO  - LoadRequest ("src" -> "UI")
2016-03-07 22:19:37.005 [JavaFX Application Thread] INFO  - LoadResponse ("src" -> "Core")
2016-03-07 22:19:43.646 [JavaFX Application Thread] INFO  - LoadFromFile ("file" -> /Users/alex/Desktop/LRRH5.dyn2, "src" -> "UI")
```

**Comment by benedictleejh** [comment]
Did it work before the change? RxScala seems to terminate a stream when an error occurs, so I'm getting the issue even on removing the error handling.
